name: ArcadeCore
version: 0.1
main: net.mutinies.arcadecore.ArcadeCorePlugin

depend: [ProtocolLib]

commands:
  game:
    description: Manages the current game
    permission: mutinies.arcadecore.game
    usage: |
      /game start
      /game stop
      /game set <gameName>
      /game list
  game start:
    description: Starts the game
  game stop:
    description: Stops the game
  game set:
    description: Sets the current game game
  game list:
    description: Lists the available game
  spec:
    description: Toggles spectator mode
    permission: mutinies.arcadecore.spec
  map:
    description: Sets current game map
    permission: mutinies.arcadecore.map
  config:
    description: Change the current game's configuration
    permission: mutinies.arcadecore.config
  pause:
    description: Change the current game's configuration
    permission: mutinies.arcadecore.pause

permissions:
  mutinies.arcadecore.*:
    children:
      mutinies.arcadecore.pause: true
  mutinies.arcadecore.game:
    default: op
  mutinies.arcadecore.map:
    default: op
  mutinies.arcadecore.config:
    default: op
  mutinies.arcadecore.pause:
    default: op
  mutinies.arcadecore.spec:
    default: true
